### ISSUE TITLE
[Typo] Faction Relation -55 through -75 labelled "Exalted"

### ISSUE THREAD

**Issue by harrisog** [mouse0270/kasper#1]
maybe relabel this tier as "Infamous" and the -75 through -100 tier as "Notorious"? 

Alternately, "Despised" and "Loathed" are also pretty strong words for deep hate and maybe better reflect the opposite of "Respected" and "Revered" on the positive side of the spectrum

**Comment by mouse0270** [comment]
This is what I get for having AI come up with my labels. I didn't even really think about what the words meant and just kinda used what chat gpt threw out. haha

I do think I like "Despised" and "Loathed" better. I will change the defaults to those. In the mean time, you should be able to change those in the settings for your personal preference. 

The default presets are more meant to be used as a guide to get you started, since everyone's campaign will different. Its why I spent so much time on making each section and faction so highly customizable.

**Comment by harrisog** [comment]
I also just realized -15 to -35 "Feared" is maybe too strong a word for that default -- "Disdained" or "Scorned" are a couple replacement candidates

**Comment by MrVauxs** [comment]
I think [Fallout New Vegas can be a good source](https://fallout.fandom.com/wiki/Fallout:_New_Vegas_reputations) of such names for reputation rankings!

**Comment by mouse0270** [comment]
I sorta wanted to use the one from FNV, but I don't understand there tables and how to convert it to be to my system. My original system would be easy because you could build more complex systems, but it was a pain to setup. Adjusting it to be <= value made the setup a lot cleaner, but less flexible.

So if you give me an idea of how the FNV one should look, I'd be happy to add a new preset.

**Comment by MrVauxs** [comment]
The thing about FNV tables is that it's a two axis system. It's not a single variable of "Good to Bad" but how much good you did and how much evil you did that then together form whatever you are on the table.

So if you are a pure soul with 10 good and 0 evil, you are **Idolized**. If you are 10 good and 3 evil, you are a **Good-Natured Rascal**. If you are completely evil you are **Vilified**, and if you are 10 good and 10 evil you are Chaotic Evil incarnate, **Wild Child**.

This requires keeping 2 variables instead of just one and keeping a two-axis table of all various names and their respective thresholds.

~~And by that point if you were to add that, it wouldn't be difficult to make it an `n`-axis chart~~

**Comment by mouse0270** [comment]
My original system, could have let you design something like that, because you really got to define as many variables and as many labels as you wanted.

But as I started to build an interface to let users customize it, it basically was overly complicated and made it so that most people would be unlikely to actually use it.

So I decided to switch to the current system, its not as flexible, but I think it will cover 99% of peoples use case and the interface is simple enough that most people could figure it out without a lengthy tutorial on how to use it.

**Comment by mouse0270** [comment]
Though in theory, once I finish the API, someone could make a module that would let you do something like this. I might have to remember this conversation so I could be an example module showing how to do more complex things like this via the API.

**Comment by mouse0270** [comment]
Should be resolved in [v1.1.0](https://github.com/mouse0270/kasper/releases/tag/1.1.0)
