### ISSUE TITLE
Players cannot see this

### ISSUE THREAD

**Issue by MotoMoto1234** [mouse0270/kasper#7]
Is there a way to make a view only version of this window the players can atleast look at?

**Comment by MotoMoto1234** [comment]
Yeah I don't trust my players with it, they always break things.

**Comment by GorgoPrimus** [comment]
Oh I thought this was player facing as well. Count me among those who'd love for there to be a read-only version with (with toggles to show particular factions to players) that players could see.

**Comment by SesuUisu** [comment]
At the moment players have the settings to change the activation method to pinned. Pinned KASPER can be seen by players if they change it. After a reload it is gone, but can be reactivated the same way. It is also editable for the user, but will have "User [...] lacks permission to update Setting [...]" and will not update on GM side (neither does it update to the player as long there is no re-activation in the settings).

**Comment by mouse0270** [comment]
Oh... shit its missing `restricted` this will be fixed. Glad they can't change it.

**Comment by mouse0270** [comment]
So I think were almost ready for the next release to handle this. https://streamable.com/ig8aly

**Comment by GorgoPrimus** [comment]
That’s awesome! While you’re working on that, is there a way you could allow partial spoilering/hiding of faction names? PF2E has formatting to allow that, but Kasper doesn’t seem to allow it’s use at the moment.

**Comment by mouse0270** [comment]
> That’s awesome! While you’re working on that, is there a way you could allow partial spoilering/hiding of faction names? PF2E has formatting to allow that, but Kasper doesn’t seem to allow it’s use at the moment. This would be helpful if you want to show faction relations to players without giving away the full name of said faction (like who its leader is).

Could you give me an example of what you mean by *PF2E has formatting to allow that* or just maybe explain exactly how you would like this work?

I assume you want to be able to hide the faction name so it shows up as something like **Unknown** instead of **Mirellia Q. Melromarc**? How would you expect a feature like this to work?

**Comment by GorgoPrimus** [comment]
There are two kinds of GM spoiler formats you can use to hide text from players until you reveal it later, and you can use them to further spoiler part of a spoiler. Here's an example from what I've been using prior to Kasper.

![Untitled](https://github.com/mouse0270/kasper/assets/126842722/315bac81-70e0-487c-9452-20a61212f44b)
![Untitled2](https://github.com/mouse0270/kasper/assets/126842722/df054bbb-1253-44dd-8918-f221c7952643)

I use GM Block Spoiler text on the entire faction name and their info to hide it all from players until they get to the Workshop and find out again them. Then I use Inline GM Spoiler text on Volluk's name so I can reveal to the players that the faction they are dealing with is a Workshop, but not reveal that it's actually Volluk's (evil dude they've heard of before) until they learn that later or run into him. Kasper, from what I can tell, doesn't allow you to put any system formatting on faction names, which means that at present (with the model shown in your demo image) I'd only be able to either show the entire name and status together or nothing.

Hope that makes sense. If using system formatting is too difficult, what I'm really after is just the utility for this use case offered by it, so if you could replicate that some other way that'd be perfect too.

Thanks for hearing me out.

**Comment by mouse0270** [comment]
Would you want to be able to hide the name, or just the hide the entire faction? Basically, I could add a right click option to hide the faction from the player? this way they wont see it until you want them too.

Or I could add an option to show `Unknown` until you reveal it to the player. Though hiding the faction would be easier, both are viable options.

**Comment by mouse0270** [comment]
> There are two kinds of GM spoiler formats in PF2E you can use to hide text from players until you reveal it later, and you can use them to further spoiler part of a spoiler. Here's an example from what I've been using prior to Kasper.
> 
> ![Untitled](https://user-images.githubusercontent.com/126842722/251631221-315bac81-70e0-487c-9452-20a61212f44b.jpg) ![Untitled2](https://user-images.githubusercontent.com/126842722/251631249-df054bbb-1253-44dd-8918-f221c7952643.jpg)
> 
> I use GM Block Spoiler text on the entire faction name and their info to hide it all from players until they get to the Workshop and find out again them. Then I use Inline GM Spoiler text on Volluk's name so I can reveal to the players that the faction they are dealing with is a Workshop, but not reveal that it's actually Volluk's (evil dude they've heard of before) until they learn that later or run into him. Kasper, from what I can tell, doesn't allow you to put any system formatting on faction names, which means that at present (with the model shown in your demo image) I'd only be able to either show the entire name and status together or nothing.
> 
> Hope that makes sense. If using system formatting is too difficult, what I'm really after is just the utility for this use case offered by it, so if you could replicate that some other way that'd be perfect too.
> 
> Thanks for hearing me out.

So this is what I have to allowing you to toggle players ability to view individual factions. But I am not really happy with the User Experience. Basically it works like this.
- Does the faction have a viewable state, always use that.
- Otherwise, use World Setting canPlayersView

So whats the problem. Once you set a faction as viewable or not viewable, it will always use that instead of the world setting, which its supposed to do, but it just feels bad to me.
https://streamable.com/8gwvmf

**Comment by mouse0270** [comment]
Right click on reputation will give you to
1. Toggle if player can view container
2. Show Container and all factions to players
3. Hide container and all factions from players

Right clicking on tracker will give you the option to
- Show tracker to player if its not currently visible
- Hide tracker from player if its currently visible

Should be resolved in [v1.1.0](https://github.com/mouse0270/kasper/releases/tag/1.1.0)

**Comment by GorgoPrimus** [comment]
Ideally I would want you to either allow text editing using whatever options system journals have on name text, or some inbuilt way to hide _part_ of the name. Use case example is if a faction is "Evil Factory" I want the option to show nothing, show it as "Factory", or show it fully as "Evil Factory"; players would eventually discover it as a faction they could interact with and see it as "Factory" at first (and unlike keeping it "Unknown" they'd think they fully know what it is now), then later on they could discover it is actually "Evil Factory" and the name could be fully revealed; and to be clear I'm not talking about having two names that toggle - I'm just only showing the second half of the same name on a line since the first half was hidden/spoilered. The alternative is having to remember it's actually "Evil Factory" and edit/write out the full name after they discover the faction they've been working with is secretly part of the Evil faction - which isn't awful but with more complicated faction names/leaders/etc is more of a pain than it'd be with this feature request.

I fully appreciate that just making it hidden, revealed, or "Unknown" is easier to do for you, but for what it's worth that's not really what I was requesting. 

And thanks either way for doing what you have; if you decided not to do more than this for names it'd still be more than you had before and I appreciate you taking the time and effort to code it.

**Comment by mouse0270** [comment]
Can you create a new issue with this as a feature request. It's not really as simple as using the GM block in the editors as this isn't really an editor field and just an input essentially...

I have an idea but it may not be what your looking for. I could add an option for you to set an alt title. Which would let you see *Evil Faction* but players will see whatever you put in the alt title.

**Comment by GorgoPrimus** [comment]
Yeah, that'd be perfect.
